### ISSUE TITLE
Changes and fixes

### ISSUE THREAD

**Issue by cubitoSempai** [View-Foundation/sgsst-release#14]
## Complaints

- [x] allow zip in in quejas.
- [x] edit title in `/quejas/revision/{id}` from 'Editar queja - agregar acciones' to 'Revisión queja'.
- [x] Allow to add name in input text from the user in `/documentos` routes
   - Employee
   - Company
   - Suppliers
- [x] Validate in before input text added if the name is the same show message with a error
- [x] Create search or  filter for files on following routes of documents
   - `/documentos/proveedores/{id}`
   - `/documentos/empresa`
   - `/documentos/empleados/{id}`

- [x] Remove required in support file when create a minutes in `/actas/{comite}/crear`

**Comment by JhanGutierrez** [comment]
**`Remember to create a new table to upload only the supplier documents`** 
@cubitoSempai
